Обновление шаблонов helm

diff --git a/front-ui/Jenkinsfile b/front-ui/Jenkinsfile
--- a/front-ui/Jenkinsfile
+++ b/front-ui/Jenkinsfile
@@ -186,6 +186,25 @@ pipeline {
                         }
                     }
                 }
+                // Необходимо наличие установленных CRD Gateway API в кластере для создания HTTPRoute
+                stage('Install Nginx Gateway Fabric if needed') {
+                    steps {
+                        sh """
+                        if ! kubectl get crds | grep gateway; then
+                          echo "CRD Gateway API not found, installing..."
+                          kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.0.1" | kubectl apply -f -
+                        else
+                            echo "CRD Gateway API already installed - skipping"
+                            if ! helm list -n nginx-gateway | grep -q ngf; then
+                                echo "Nginx Gateway Fabric not found, installing..."
+                                helm upgrade --install ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway
+                            else
+                              echo "Nginx Gateway Fabric already installed — skipping config and upgrade."
+                            fi
+                        fi
+                        """
+                    }
+                }
                 stage('Install Keycloak if needed') {
                     steps {
                         sh """
diff --git a/transfer-service/Jenkinsfile b/transfer-service/Jenkinsfile
--- a/transfer-service/Jenkinsfile
+++ b/transfer-service/Jenkinsfile
@@ -200,6 +200,35 @@ pipeline {
                         }
                     }
                 }
+                // Необходимо наличие установленных CRD Gateway API в кластере для создания HTTPRoute
+                stage('Install Nginx Gateway Fabric if needed') {
+                    steps {
+                      sh """
+                      if ! kubectl get crd gateways.gateway.networking.k8s.io >/dev/null 2>&1; then
+                        echo "CRD Gateway API not found, installing..."
+                        kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.0.1" | kubectl apply -f -
+                      else
+                        echo "CRD Gateway API already installed - skipping"
+                      fi
+
+                      if ! helm list -n nginx-gateway | grep -q ngf; then
+                        echo "Nginx Gateway Fabric not found, installing..."
+                        helm upgrade --install ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric \\
+                          --create-namespace -n nginx-gateway \\
+                          --set service.type=LoadBalancer
+
+                        echo "Waiting for NGF deployment to be ready..."
+                        kubectl rollout status deployment/ngf-nginx-gateway-fabric -n nginx-gateway --timeout=60s
+
+                        echo "Creating Gateway object..."
+                        kubectl apply -f bank-app/templates/gateway.yaml
+                      else
+                        echo "Nginx Gateway Fabric already installed — skipping config and upgrade."
+                      fi
+                      """
+                    }
+
+                }
                 stage('Install Keycloak if needed') {
                     steps {
                         sh """
